/* GENERATED by the lab's gen_body_layout.py from the Python modules - do not edit by hand. */
#pragma once

/* game: ULES01213 (EU). FUComplete (JP ULJM05500) will need its own values or a signature search */
/* the comrade */
#define CAT_PTR 0x9A4F08Cu
#define QUEST_TIMER 0x9A05DD0u
#define QUEST_ID 0x9A064D4u
#define R_BEHAVIOUR 0x299u
#define R_PHASE 0x120Cu
#define R_ANIM 0x324u
#define R_HP 0x2E4u
#define R_HP_MAX 0x41Eu
#define R_ZONE 0x29Au
#define R_PARALYSIS 0x458u
#define R_POS 0x40u
#define R_LEVEL 0x11C0u
#define R_ATTACK_TYPE 0x11E8u
#define R_WEIGHTS 0x11E9u
#define R_TIER 0x11D8u
#define R_SKILLS 0x11E0u
#define R_ATTACK 0x11C8u
#define R_DEFENCE 0x11CCu
/* the hunters (ram/layout.py) */
#define PLAYER_TABLE 0x90B3440u
#define PLAYER_STRIDE 0xA7F0u
#define PLAYER_SLOTS 0x4u
#define P_HP 0x2E4u
#define P_STAMINA 0x55Au
#define P_STAMINA_MAX 0x62Eu
#define HP_MAX 0x96u
#define H_ACT_TYPE 0x298u
#define H_ACT_ID 0x299u
#define H_CROUCH 0x280u
#define H_POISON 0x388u
#define H_ATTACK_UP 0x3D6u
#define H_DEFENCE_UP 0x3DAu
/* the monsters */
#define MONSTER_LIST_PTR 0x9C121B0u
#define MONSTER_LIST_OFF 0x1220u
#define MONSTER_LIST_N 0x14u
#define M_ACT_TYPE 0x298u
#define M_SPECIES 0x1E8u
#define M_FLAGS 0x638u
#define M_LARGE 0x4u
/* the placed objects (objects.py): the scan, the trap types in protocol order (TRAP_IDS) */
#define POOL_LO 0x9C00000u
#define POOL_HI 0x9C40000u
#define STATIC_LO 0x8800000u
#define STATIC_HI 0x8A00000u
#define TRAP_TYPE_0 0x89BDA5Cu
#define TRAP_TYPE_1 0x89BD4B0u
#define TRAP_TYPE_2 0x89BD548u
/* the hooks (hook.py): game code */
#define THINK 0x9A75A80u
#define ENTER_BEHAVIOUR 0x9A77750u
#define ENTER_ORIGINAL_0 0x27BDFFA0u
#define ENTER_ORIGINAL_1 0xAFBF000Cu
#define NAME_SITE 0x8891434u
#define NAME_SITE_ORIGINAL 0x2203821u
#define NAME_RETURN 0x889143Cu
#define REC_WEIGHTS 0x11E9u
#define REC_SKILLS 0x11E0u
#define HIT_SITE 0x9C44C34u
#define HIT_CALLEE 0x9C44F08u
#define HIT_SITE_ORIGINAL 0xE7113C2u
#define HIT_RING_N 0x20u
#define HIT_ENTRY 0xCu
#define THINK_CALLS 0x43u
/* the hooks: the block (any base) */
#define BLOCK_SIZE 0x1000u
#define OFF_MAILBOX 0x80u
#define OFF_LOCK 0x81u
#define OFF_LOG_PROPOSAL 0x94u
#define OFF_LOG_REPLACED 0x95u
#define OFF_LOG_COUNT 0x96u
#define OFF_RING_IDX 0x98u
#define OFF_LEASE 0xA0u
#define OFF_LOG_LOST 0xA4u
#define OFF_NAME_SRC 0xA8u
#define OFF_CARD_FLAG 0xACu
#define OFF_CARD_REC 0xB0u
#define OFF_CARD_WEIGHTS 0xB4u
#define OFF_CARD_SKILLS 0xB8u
#define OFF_CAVE 0x100u
#define OFF_TABLE 0x200u
#define OFF_RING 0x400u
#define OFF_NAME_BUF 0x480u
#define OFF_CAVE3 0x500u
#define OFF_CAVE2 0x600u
#define OFF_HIT_IDX 0x9Cu
#define OFF_CAVE4 0x800u
#define OFF_HIT_RING 0x900u
#define OFF_CAVE_CALL 0xB00u
#define TABLE_SIZE 0x40u
#define RING_SIZE 0x40u
#define EMPTY 0xFFu
#define LOST 0x80u
#define NAME_BUF_SIZE 0x20u
/* the card (card.py, nature.py) */
#define GLOBAL 0x89CC438u
#define SLOTS_OFF 0x69BECu
#define SLOT_STRIDE 0x70u
#define SLOT_COUNT 0x3u
#define EQUIPPED 0x2u
#define NAME_LIST 0x89B2E7Cu
#define NAME_LIST_SIZE 0x800u
#define TRAINING_OFF 0x5B1u
#define BLOCK_OFF 0x624u
#define NAME_FIELD 0x14u
#define N_SKILLS 0x24u
#define BAKED_SKILLS_MASK 0x40200240u
#define N_PERSONALITIES 0x10u
/* protocol v1 (protocol.py) */
#define OT_MAGIC 0x544Fu
#define OT_VERSION 0x1u
#define OT_PORT 0x1E61u
#define T_HELLO 0x0u
#define T_SENSE 0x1u
#define T_TABLE 0x2u
#define T_BYE 0x3u
#define MAX_MONSTERS 0x14u
#define MAX_PROPOSALS 0x10u
#define MAX_HITS 0x8u
#define MAX_OBJECTS 0x4u
#define MAX_BYTES 0x400u
#define TABLE_MSG_SIZE 0x5Cu
/* the personalities weights (255 = never attacks), by personality id */
#define PREF_WEIGHTS_INIT {{50, 50, 50, 50}, {0, 50, 50, 0}, {30, 50, 50, 50}, {70, 50, 50, 25}, {100, 50, 50, 25}, {70, 95, 70, 0}, {70, 80, 70, 25}, {30, 30, 30, 50}, {30, 15, 30, 50}, {30, 50, 100, 50}, {70, 50, 100, 25}, {30, 50, 0, 50}, {70, 50, 0, 25}, {0, 95, 100, 0}, {100, 50, 0, 25}, {255, 50, 0, 50}}
